create schema if not exists scheduler;

create table if not exists scheduler.schedules(
    id int generated by default as identity primary key,
    name text,
    srcpath text not null,
    destpath text not null,
    cronexpression text not null
);
