create schema if not exists scheduler;

create table if not exists scheduler.schedules(
    id int generated by default as identity primary key,
    name text,
    srcpath text not null,
    destpath text not null,
    cronexpression text not null
);

alter table scheduler.schedules add column if not exists enabled boolean default true;

create table if not exists scheduler.backupruntype(
    id smallint primary key,
    name text not null
);

insert into scheduler.backupruntype(id, name)
values 
(1, 'scheduled'),
(2, 'adhoc')
on conflict(id) do nothing;

create table if not exists scheduler.backuprunstatus (
    id smallint primary key,
    name text not null
);

insert into scheduler.backuprunstatus(id, name)
values
(1, 'running'),
(2, 'completed')
on conflict(id) do nothing;

create table if not exists scheduler.backupruns(
    id int generated by default as identity primary key,
    backupruntype int not null,
    scheduleid int,
    status int not null,
    starttime timestamp not null default now(),
    completedat timestamp,
    exitcode int,
    logs text
);

alter table scheduler.backupruns alter column starttime drop default;
alter table scheduler.backupruns alter column starttime drop not null;

insert into scheduler.backuprunstatus(id, name)
values
(3, 'submitted')
on conflict(id) do nothing;



